name: Multi-platform CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup JDK (for Android)
      if: matrix.os == 'ubuntu-latest'
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Build Debug APK (for Android)
      if: matrix.os == 'ubuntu-latest'
      run: ./gradlew assembleDebug

    - name: Build APK
      if: matrix.os == 'ubuntu-latest'
      run: flutter build apk

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: app-release
        if: matrix.os == 'ubuntu-latest'
        path: build/app/outputs/flutter-apk/app-release.apk

